/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package powermock_testJ4;

import powermock_testJ4.service.Service;
import powermock_testJ4.service.DummyRunner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        new Service().execute();
    }
}
