/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logbacktest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import logbacktest.layerone.LogOne;
import logbacktest.layertwo.LogTwo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        outputLog();
    }

    private static void outputLog() {
        Logger logger = LoggerFactory.getLogger(App.class);
        logger.trace("App Trace");
        logger.debug("App Debug");
        logger.info("App Info");
        logger.warn("App Warn");
        logger.error("App Error");
        new LogOne().outputLog();
        new LogTwo().outputLog();
    }
}
