/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_type_test;

import java.util.List;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Arrays;
import java_type_test.element.Element;

public class App {
    public static void main(String[] args) {
        Field[] fields = Sample.class.getDeclaredFields();

        Arrays.stream(fields).flatMap(f -> Arrays.stream(f.getType().getDeclaredFields()))
             .map(f -> f.getGenericType().getTypeName()).forEach(System.out::println);

        Arrays.stream(fields).map(f -> f.getGenericType().getTypeName()).forEach(System.out::println);

    }

    class Sample {
        Element e = new Element();
    }
}
